services:
  mysql-1:
    image: mysql:latest
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ordersdb
      TZ: Asia/Seoul
    ports:
      - 3306:3306

  mysql-2:
    image: mysql:latest
    container_name: mysql-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: paymentsdb
      TZ: Asia/Seoul
    ports:
      - 3307:3306